// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20210611192048_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Age")
                        .HasColumnType("double");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3) CHARACTER SET utf8mb4");

                    b.HasKey("PetId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetId = 3,
                            Age = 1.2,
                            Breed = "Maine Coon",
                            Description = "Massive fat cat; looking to be ~25lbs when fully grown",
                            Gender = "Female",
                            Name = "Mango",
                            Type = "Cat"
                        },
                        new
                        {
                            PetId = 4,
                            Age = 8.5,
                            Breed = "Chiwawa",
                            Description = "Mi quero Taco Bell",
                            Gender = "Female",
                            Name = "Taco",
                            Type = "Dog"
                        },
                        new
                        {
                            PetId = 5,
                            Age = 4.0,
                            Breed = "Great Dane",
                            Description = "Long Haired; White/Orangish in color",
                            Gender = "Male",
                            Name = "Sebashian",
                            Type = "Dog"
                        },
                        new
                        {
                            PetId = 6,
                            Age = 12.0,
                            Breed = "Golden Retriever",
                            Description = "Golden in color; great with kids",
                            Gender = "Male",
                            Name = "Doug",
                            Type = "Dog"
                        },
                        new
                        {
                            PetId = 7,
                            Age = 3.75,
                            Breed = "Calico",
                            Description = "Long Haired; very fiesty; loves tuna treats",
                            Gender = "Female",
                            Name = "Meow",
                            Type = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
